export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const GET_USER = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USER_SUCCESS";
export const GET_USERS_FAILED = "GET_USER_FAILED";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

export const CREATE_QUESTION = "CREATE_QUESTION";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAILED = "CREATE_QUESTION_FAILED";
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_QUESTIONS_FAILED = "GET_QUESTIONS_FAILED";
export const IS_POLL_SHOWN = "IS_POLL_SHOWN";

export const GET_POLL_DETAILS = "GET_POLL_DETAILS";
export const STORE_POLL_DETAILS = "STORE_POLL_DETAILS";

export const UI_LOADER = "UI_LOADER";